services:
  s3-api:
    image: reyanpy/async-fastapi-s3:latest
    container_name: files-api
    env_file:
      - .env
    environment:
      S3_SERVER_ENDPOINT: http://minio:9000
    ports:
      - 8090:8090
    depends_on:
        - minio
    profiles:
      - full

  minio:
    image: minio/minio
    container_name: minio_server
    restart: always
    volumes:
      - minio_volume:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001


volumes:
  minio_volume:
