name: Docker push

on:
  workflow_run:
    workflows: ["Linter check", "Run tests"]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: reyanpy/async-fastapi-s3:latest
